### ISSUE TITLE
[FAIL. Reason: Governor: vote not currently active] testGovernanceUpdatesBox() (gas: 249539)

### ISSUE THREAD

**Issue by iftikharuddin** [Cyfrin/foundry-dao-f23#3]
Following foundry-dao tutorials i was going to test `testGovernanceUpdatesBox` function and I am getting this error when i run `forge test --match-test testGovernanceUpdatesBox -vvv` in the terminal.

**Error:**

```
[FAIL. Reason: Governor: vote not currently active] testGovernanceUpdatesBox() (gas: 249539)
```

**Source code:**

```
function testGovernanceUpdatesBox() public {
        uint256 valueToStore = 777;
        string memory description = "Store 1 in Box";
        bytes memory encodedFunctionCall = abi.encodeWithSignature("store(uint256)", valueToStore);
        addressesToCall.push(address(box));
        values.push(0);
        functionCalls.push(encodedFunctionCall);
        // 1. Propose to the DAO
        uint256 proposalId = governor.propose(addressesToCall, values, functionCalls, description);
        vm.warp(block.timestamp + VOTING_DELAY + 1);
        vm.roll(block.number + VOTING_DELAY + 1);

        // 2. Vote
        string memory reason = "I like a do da cha cha";
        // 0 = Against, 1 = For, 2 = Abstain for this example
        uint8 voteWay = 1;
        vm.prank(VOTER);
        governor.castVoteWithReason(proposalId, voteWay, reason);

        vm.warp(block.timestamp + VOTING_PERIOD + 1);
        vm.roll(block.number + VOTING_PERIOD + 1);

        // 3. Queue
        bytes32 descriptionHash = keccak256(abi.encodePacked(description));
        governor.queue(addressesToCall, values, functionCalls, descriptionHash);
        vm.roll(block.number + MIN_DELAY + 1);
        vm.warp(block.timestamp + MIN_DELAY + 1);

        // 4. Execute
        governor.execute(addressesToCall, values, functionCalls, descriptionHash);

        assert(box.retrieve() == valueToStore);
    }
```
**My code snap**: 

<img width="1013" alt="image" src="https://github.com/Cyfrin/foundry-dao-f23/assets/10365184/20b90321-48a2-42f8-b6f3-7082dacdfd23">

Console Error: <img width="1397" alt="image" src="https://github.com/Cyfrin/foundry-dao-f23/assets/10365184/53a8a755-5b91-46c9-a085-50c82dcea777">

**Note**: I know Patrick fixed it by changing wrap to roll in the tutorial but it didn't work for me so sharing it here now :pray:

All source code I deployed @ https://github.com/iftikharuddin/foundry-dao

**Comment by PatrickAlphaC** [comment]
Hmm.... if you fork this repo do you get the same issue?

**Comment by iftikharuddin** [comment]
Hey champ,

Actually i was practicing with your video from scratch but I will try forking 🙏

**Comment by iftikharuddin** [comment]
seems like the forking is working fine, not sure why it didn't worked with my code. I will dig more 🙏 
<img width="708" alt="image" src="https://github.com/Cyfrin/foundry-dao-f23/assets/10365184/45e00c2b-2283-45eb-8f76-e76aea717bdd">
