### ISSUE TITLE
No Arguments Passed in the base constructor of Ownable in Box.sol 

### ISSUE THREAD

**Issue by kingmanas** [Cyfrin/foundry-dao-f23#5]
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

contract Box is Ownable {
    uint256 private value;

    **constructor() Ownable(msg.sender) {}** // it has to included for the code to run
![Issue](https://github.com/Cyfrin/foundry-dao-f23/assets/110822154/f4a016dc-84a3-4daa-9835-0abb8596e16b)

    
    event ValueChanged(uint256 newValue);

    
    function store(uint256 newValue) public onlyOwner {
        value = newValue;
        emit ValueChanged(newValue);
    }

   
    function retrieve() public view returns (uint256) {
        return value;
    }
}

**Comment by PatrickAlphaC** [comment]
Thanks! You're using a newer version of the Ownable contracts. If you clone this repo, you'll find it works the same as the video.

To fix this, you can also just use `msg.sender` in the `Ownable` constructor, like so:

```diff
contract Box is Ownable {

+  constructor() Ownable(msg.sender) {}
```
