### ISSUE TITLE
GovernorUnexpectedProposalState Revert

### ISSUE THREAD

**Issue by kingmanas** [Cyfrin/foundry-dao-f23#6]
![issue2](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/2aa23f2f-4558-4c88-94e8-797218f9ffe5/237721d3-70e3-44d1-a837-55738355aa9b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My8yYWEyM2YyZi00NTU4LTRjODgtOTRlOC03OTcyMThmOWZmZTUvMjM3NzIxZDMtNzBlMy00NGQxLWE4MzctNTU3MzgzNTVhYTliIiwiaWF0IjoxNzE0MTU5Mzg0LCJleHAiOjMzMjg0NzE5Mzg0fQ.pgk9ahnUbIOS_RWVXeB4NkTuYxVHi_7-5dykBB6pjoU)

I have checked everything and still not able to figure out the real issue why its reverting
My test Function

![issue3](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/7b7f849c-665d-4e08-a72c-b931763499c8/815568d2-39e2-4f3c-a95c-e87eafe49076?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My83YjdmODQ5Yy02NjVkLTRlMDgtYTcyYy1iOTMxNzYzNDk5YzgvODE1NTY4ZDItMzllMi00ZjNjLWE5NWMtZTg3ZWFmZTQ5MDc2IiwiaWF0IjoxNzE0MTU5Mzg0LCJleHAiOjMzMjg0NzE5Mzg0fQ.3TgtNwMNvnrvALNqGfcv_FE_CCwmEHDTrqDFh9GT0V4)

**Comment by kingmanas** [comment]
I also tried  // **governor.proposalSnapshot(proposalId);**

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discussion on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464
